export { DepartmentListPage } from './pages/department-list-page'
export { DepartmentCreatePage } from './pages/department-create-page'
export { useDepartments } from './api/use-departments'
export { useDepartment } from './api/use-department'
export type { Department } from './types'
