export { useDistricts } from './api/use-districts'
export { useDistrictsInfinite } from './api/use-districts-infinite'
export { useDistrictSelect, type DistrictSelect } from './hooks/use-district-select'
export { fetchDistricts, fetchDistrictPage, ensureDistricts } from './api/district-api'
export type { DistrictRecord } from './types'
